Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

# Modify organizations
Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"

  - &org1Name
    Name: ${ORG1_MSPNAME}
    ID: ${ORG1_MSPNAME}
    MSPDir: crypto-config/peerOrganizations/${ORG1_DOMAIN}/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('${ORG1_MSPNAME}.member')"
      Writers:
        Type: Signature
        Rule: "OR('${ORG1_MSPNAME}.admin', '${ORG1_MSPNAME}.client')"
      Admins:
        Type: Signature
        Rule: "OR('${ORG1_MSPNAME}.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('${ORG1_MSPNAME}.peer')"
    AnchorPeers:
      - Host: ${PEER0_ORG1_DOMAIN} # define dns / ip address if using multihost technique
        Port: ${PEER0_ORG1_PORT} # define port

  - &org2Name
    Name: ${ORG2_MSPNAME}
    ID: ${ORG2_MSPNAME}
    MSPDir: crypto-config/peerOrganizations/${ORG2_DOMAIN}/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('${ORG2_MSPNAME}.member')"
      Writers:
        Type: Signature
        Rule: "OR('$ORG2_MSPNAME.admin', '$ORG2_MSPNAME.client')"
      Admins:
        Type: Signature
        Rule: "OR('${ORG2_MSPNAME}.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('${ORG2_MSPNAME}.peer')"
    AnchorPeers:
      - Host: ${PEER0_ORG2_DOMAIN}
        Port: ${PEER0_ORG2_PORT}

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft # define consensus type, either solo or etcdraft
  Addresses:
    - orderer.example.com:${ORDERER_MAIN_PORT}
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities
  EtcdRaft: # if using solo consensus, remove this field
    Consenters:
      - Host: orderer.example.com
        Port: ${ORDERER_MAIN_PORT}
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      - Host: ${ORDERER1_ORG1_DOMAIN}
        Port: ${ORDERER1_ORG1_PORT}
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/${ORDERER1_ORG1_DOMAIN}/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/${ORDERER1_ORG1_DOMAIN}/tls/server.crt
      - Host: ${ORDERER2_ORG2_DOMAIN}
        Port: ${ORDERER2_ORG2_PORT}
        ClientTLSCert: crypto-config/ordererOrganizations/example.com/orderers/${ORDERER2_ORG2_DOMAIN}/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/example.com/orderers/${ORDERER2_ORG2_DOMAIN}/tls/server.crt

Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium: # rename based on Consortium name on ChannelProfile
        Organizations:
          - *org1Name
          - *org2Name

  ChannelProfile:
    <<: *ChannelDefaults
    Consortium: ${CONSORTIUM_NAME} # Rename Consortium name based on needs.
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *org1Name
        - *org2Name
