# Orderer Definition
# Note: if using raft consensus, define n+1 orderers.
#       if using solo consensus, just define 1 orderer (orderer.example.com)
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
        SANS:
          - orderer.example.com
          - ${PEER0_ORG1_HOST_IPADDRESS}
      - Hostname: ${ORDERER1_ORG1_NAME}
        SANS:
          - ${ORDERER1_ORG1_DOMAIN}
          - ${PEER0_ORG1_HOST_IPADDRESS}
      - Hostname: ${ORDERER2_ORG2_NAME}
        SANS:
          - ${ORDERER2_ORG2_DOMAIN}
          - ${PEER0_ORG2_HOST_IPADDRESS}

# Peer Definition
# Note: Peer name orderer starts from 0. peer0, peer1, etc.
PeerOrgs:
  - Name: ${ORG1_NAME}
    Domain: ${ORG1_DOMAIN}
    EnableNodeOUs: true
    Template:
      Count: 1 # How many peer will be generated
    Users:
      Count: 1 # The number of user accounts _in addition_ to Admin
    Specs:
      - Hostname: peer0
        SANS:
          - ${PEER0_ORG1_DOMAIN}
          - ${PEER0_ORG1_HOST_IPADDRESS}

  - Name: ${ORG2_NAME}
    Domain: ${ORG2_DOMAIN}
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - ${PEER0_ORG2_DOMAIN}
          - ${PEER0_ORG2_HOST_IPADDRESS}
