# Orderer Definition
# Note: if using raft consensus, define n+1 orderers.
#       if using solo consensus, just define 1 orderer (orderer.example.com)
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
        SANS:
          - orderer.example.com
          - 10.216.74.143


# Peer Definition
# Note: Peer name orderer starts from 0. peer0, peer1, etc.
PeerOrgs:
  - Name: lnsw1
    Domain: lnsw1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1 # How many peer will be generated
    Users:
      Count: 1 # The number of user accounts _in addition_ to Admin
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.lnsw1.example.com
          - 10.216.74.143

  - Name: lnsw2
    Domain: lnsw2.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
    Specs:
      - Hostname: peer0
        SANS:
          - peer0.lnsw2.example.com
          - 10.216.74.146
